version: "3.8"

services:
  shopping-system-keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: "shopping-system-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080